// <auto-generated />
using System;
using JournalMVC.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JournalMVC.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240526154224_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JournalMVC.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeIntervalId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId");

                    b.HasIndex("TimeIntervalId");

                    b.HasIndex("TypeId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            DailyRecordId = 2,
                            Description = "Плавание",
                            TimeIntervalId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            DailyRecordId = 2,
                            Description = "Посещение выставки",
                            TimeIntervalId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            DailyRecordId = 2,
                            Description = "Игра на музыкальных инструментах",
                            TimeIntervalId = 5,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            DailyRecordId = 3,
                            Description = "Приготовление пиццы",
                            TimeIntervalId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            DailyRecordId = 3,
                            Description = "Вышивание крестиком",
                            TimeIntervalId = 7,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 8,
                            DailyRecordId = 4,
                            Description = "Изучение нового языка",
                            TimeIntervalId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 9,
                            DailyRecordId = 4,
                            Description = "Фотосъемка природы",
                            TimeIntervalId = 9,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 10,
                            DailyRecordId = 4,
                            Description = "Посещение парка развлечений",
                            TimeIntervalId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            Id = 11,
                            DailyRecordId = 5,
                            Description = "Футбол с друзьями",
                            TimeIntervalId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            DailyRecordId = 5,
                            Description = "Чтение стихов",
                            TimeIntervalId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            DailyRecordId = 7,
                            Description = "Утренняя пробежка",
                            TimeIntervalId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            DailyRecordId = 7,
                            Description = "Посещение художественной галереи",
                            TimeIntervalId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 15,
                            DailyRecordId = 7,
                            Description = "Игра на фортепиано",
                            TimeIntervalId = 5,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 16,
                            DailyRecordId = 8,
                            Description = "Приготовление суши",
                            TimeIntervalId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 17,
                            DailyRecordId = 8,
                            Description = "Вязание шарфа",
                            TimeIntervalId = 7,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 18,
                            DailyRecordId = 10,
                            Description = "Уроки рисования",
                            TimeIntervalId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 19,
                            DailyRecordId = 10,
                            Description = "Фотосессия в городском парке",
                            TimeIntervalId = 9,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 20,
                            DailyRecordId = 10,
                            Description = "Посещение кинотеатра",
                            TimeIntervalId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            Id = 21,
                            DailyRecordId = 11,
                            Description = "Баскетбол на открытом воздухе",
                            TimeIntervalId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            DailyRecordId = 11,
                            Description = "Чтение на скамейке в парке",
                            TimeIntervalId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            DailyRecordId = 13,
                            Description = "Утренняя йога",
                            TimeIntervalId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            DailyRecordId = 13,
                            Description = "Посещение музея истории",
                            TimeIntervalId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 25,
                            DailyRecordId = 13,
                            Description = "Игра на гитаре",
                            TimeIntervalId = 5,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 26,
                            DailyRecordId = 14,
                            Description = "Приготовление салатов",
                            TimeIntervalId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 27,
                            DailyRecordId = 14,
                            Description = "Вышивка крестом",
                            TimeIntervalId = 7,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 28,
                            DailyRecordId = 16,
                            Description = "Изучение программирования",
                            TimeIntervalId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 29,
                            DailyRecordId = 16,
                            Description = "Фотосъемка городского пейзажа",
                            TimeIntervalId = 9,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 30,
                            DailyRecordId = 16,
                            Description = "Посещение театра",
                            TimeIntervalId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            Id = 31,
                            DailyRecordId = 17,
                            Description = "Волейбол на пляже",
                            TimeIntervalId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            DailyRecordId = 17,
                            Description = "Чтение комиксов",
                            TimeIntervalId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 33,
                            DailyRecordId = 19,
                            Description = "Утренняя пробежка по парку",
                            TimeIntervalId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            DailyRecordId = 19,
                            Description = "Посещение выставки современного искусства",
                            TimeIntervalId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 35,
                            DailyRecordId = 19,
                            Description = "Игра на скрипке",
                            TimeIntervalId = 5,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 36,
                            DailyRecordId = 20,
                            Description = "Приготовление пасты",
                            TimeIntervalId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 37,
                            DailyRecordId = 20,
                            Description = "Вышивание ковра",
                            TimeIntervalId = 7,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 38,
                            DailyRecordId = 22,
                            Description = "Изучение фотографии",
                            TimeIntervalId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 39,
                            DailyRecordId = 22,
                            Description = "Фотосессия на природе",
                            TimeIntervalId = 9,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 40,
                            DailyRecordId = 22,
                            Description = "Поход в аквапарк",
                            TimeIntervalId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            Id = 41,
                            DailyRecordId = 23,
                            Description = "Футбольный матч с коллегами",
                            TimeIntervalId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            DailyRecordId = 23,
                            Description = "Чтение журнала в кафе",
                            TimeIntervalId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 43,
                            DailyRecordId = 25,
                            Description = "Утренний забег по парку",
                            TimeIntervalId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 44,
                            DailyRecordId = 25,
                            Description = "Посещение галереи современного искусства",
                            TimeIntervalId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 45,
                            DailyRecordId = 25,
                            Description = "Игра на фортепиано",
                            TimeIntervalId = 5,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 46,
                            DailyRecordId = 26,
                            Description = "Приготовление суши дома",
                            TimeIntervalId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 47,
                            DailyRecordId = 26,
                            Description = "Вышивание картины по номерам",
                            TimeIntervalId = 7,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 48,
                            DailyRecordId = 28,
                            Description = "Изучение истории искусства",
                            TimeIntervalId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 49,
                            DailyRecordId = 28,
                            Description = "Фотосессия в парке осенних красок",
                            TimeIntervalId = 9,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 50,
                            DailyRecordId = 28,
                            Description = "Поход в кино на новый фильм",
                            TimeIntervalId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            Id = 51,
                            DailyRecordId = 29,
                            Description = "Волейбол на пляже с друзьями",
                            TimeIntervalId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 52,
                            DailyRecordId = 29,
                            Description = "Чтение книги в парке",
                            TimeIntervalId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 53,
                            DailyRecordId = 31,
                            Description = "Утренняя пробежка в парке",
                            TimeIntervalId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 54,
                            DailyRecordId = 31,
                            Description = "Посещение музея истории города",
                            TimeIntervalId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 55,
                            DailyRecordId = 31,
                            Description = "Игра на пианино",
                            TimeIntervalId = 5,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 56,
                            DailyRecordId = 32,
                            Description = "Приготовление горячего шоколада",
                            TimeIntervalId = 6,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 57,
                            DailyRecordId = 32,
                            Description = "Вышивание картины крестиком",
                            TimeIntervalId = 7,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 58,
                            DailyRecordId = 34,
                            Description = "Изучение астрономии",
                            TimeIntervalId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 59,
                            DailyRecordId = 34,
                            Description = "Ночная фотосъемка звездного неба",
                            TimeIntervalId = 9,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 60,
                            DailyRecordId = 34,
                            Description = "Посещение концерта классической музыки",
                            TimeIntervalId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            Id = 61,
                            DailyRecordId = 35,
                            Description = "Футбол на стадионе",
                            TimeIntervalId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 62,
                            DailyRecordId = 35,
                            Description = "Чтение книги у камина",
                            TimeIntervalId = 2,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("JournalMVC.Models.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyRecordId");

                    b.ToTable("DailyRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = 1,
                            MonthlyRecordId = 1
                        },
                        new
                        {
                            Id = 2,
                            Day = 15,
                            MonthlyRecordId = 1
                        },
                        new
                        {
                            Id = 3,
                            Day = 30,
                            MonthlyRecordId = 1
                        },
                        new
                        {
                            Id = 4,
                            Day = 7,
                            MonthlyRecordId = 2
                        },
                        new
                        {
                            Id = 5,
                            Day = 18,
                            MonthlyRecordId = 2
                        },
                        new
                        {
                            Id = 6,
                            Day = 28,
                            MonthlyRecordId = 2
                        },
                        new
                        {
                            Id = 7,
                            Day = 3,
                            MonthlyRecordId = 3
                        },
                        new
                        {
                            Id = 8,
                            Day = 19,
                            MonthlyRecordId = 3
                        },
                        new
                        {
                            Id = 9,
                            Day = 31,
                            MonthlyRecordId = 3
                        },
                        new
                        {
                            Id = 10,
                            Day = 5,
                            MonthlyRecordId = 4
                        },
                        new
                        {
                            Id = 11,
                            Day = 20,
                            MonthlyRecordId = 4
                        },
                        new
                        {
                            Id = 12,
                            Day = 29,
                            MonthlyRecordId = 4
                        },
                        new
                        {
                            Id = 13,
                            Day = 8,
                            MonthlyRecordId = 5
                        },
                        new
                        {
                            Id = 14,
                            Day = 16,
                            MonthlyRecordId = 5
                        },
                        new
                        {
                            Id = 15,
                            Day = 25,
                            MonthlyRecordId = 5
                        },
                        new
                        {
                            Id = 16,
                            Day = 4,
                            MonthlyRecordId = 6
                        },
                        new
                        {
                            Id = 17,
                            Day = 17,
                            MonthlyRecordId = 6
                        },
                        new
                        {
                            Id = 18,
                            Day = 27,
                            MonthlyRecordId = 6
                        },
                        new
                        {
                            Id = 19,
                            Day = 9,
                            MonthlyRecordId = 7
                        },
                        new
                        {
                            Id = 20,
                            Day = 21,
                            MonthlyRecordId = 7
                        },
                        new
                        {
                            Id = 21,
                            Day = 30,
                            MonthlyRecordId = 7
                        },
                        new
                        {
                            Id = 22,
                            Day = 6,
                            MonthlyRecordId = 8
                        },
                        new
                        {
                            Id = 23,
                            Day = 19,
                            MonthlyRecordId = 8
                        },
                        new
                        {
                            Id = 24,
                            Day = 31,
                            MonthlyRecordId = 8
                        },
                        new
                        {
                            Id = 25,
                            Day = 5,
                            MonthlyRecordId = 9
                        },
                        new
                        {
                            Id = 26,
                            Day = 18,
                            MonthlyRecordId = 9
                        },
                        new
                        {
                            Id = 27,
                            Day = 29,
                            MonthlyRecordId = 9
                        },
                        new
                        {
                            Id = 28,
                            Day = 7,
                            MonthlyRecordId = 10
                        },
                        new
                        {
                            Id = 29,
                            Day = 16,
                            MonthlyRecordId = 10
                        },
                        new
                        {
                            Id = 30,
                            Day = 27,
                            MonthlyRecordId = 10
                        },
                        new
                        {
                            Id = 31,
                            Day = 8,
                            MonthlyRecordId = 11
                        },
                        new
                        {
                            Id = 32,
                            Day = 20,
                            MonthlyRecordId = 11
                        },
                        new
                        {
                            Id = 33,
                            Day = 28,
                            MonthlyRecordId = 11
                        },
                        new
                        {
                            Id = 34,
                            Day = 3,
                            MonthlyRecordId = 12
                        },
                        new
                        {
                            Id = 35,
                            Day = 15,
                            MonthlyRecordId = 12
                        },
                        new
                        {
                            Id = 36,
                            Day = 25,
                            MonthlyRecordId = 12
                        });
                });

            modelBuilder.Entity("JournalMVC.Models.MonthlyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonthlyRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Month = 1
                        },
                        new
                        {
                            Id = 2,
                            Month = 2
                        },
                        new
                        {
                            Id = 3,
                            Month = 3
                        },
                        new
                        {
                            Id = 4,
                            Month = 4
                        },
                        new
                        {
                            Id = 5,
                            Month = 5
                        },
                        new
                        {
                            Id = 6,
                            Month = 6
                        },
                        new
                        {
                            Id = 7,
                            Month = 7
                        },
                        new
                        {
                            Id = 8,
                            Month = 8
                        },
                        new
                        {
                            Id = 9,
                            Month = 9
                        },
                        new
                        {
                            Id = 10,
                            Month = 10
                        },
                        new
                        {
                            Id = 11,
                            Month = 11
                        },
                        new
                        {
                            Id = 12,
                            Month = 12
                        });
                });

            modelBuilder.Entity("JournalMVC.Models.TimeInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndActivity")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartActivity")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TimeIntervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndActivity = new TimeSpan(0, 9, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndActivity = new TimeSpan(0, 10, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndActivity = new TimeSpan(0, 11, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndActivity = new TimeSpan(0, 12, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndActivity = new TimeSpan(0, 13, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            EndActivity = new TimeSpan(0, 14, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            EndActivity = new TimeSpan(0, 15, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EndActivity = new TimeSpan(0, 16, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            EndActivity = new TimeSpan(0, 17, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            EndActivity = new TimeSpan(0, 18, 0, 0, 0),
                            StartActivity = new TimeSpan(0, 17, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("JournalMVC.Models.TypeActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Спорт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Чтение"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Путешествия"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Искусство"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Музыка"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Кулинария"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Рукоделие"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Обучение"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Фотография"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Развлечения"
                        });
                });

            modelBuilder.Entity("JournalMVC.Models.Activity", b =>
                {
                    b.HasOne("JournalMVC.Models.DailyRecord", "DailyRecord")
                        .WithMany("Activities")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JournalMVC.Models.TimeInterval", "TimeInterval")
                        .WithMany()
                        .HasForeignKey("TimeIntervalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JournalMVC.Models.TypeActivity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");

                    b.Navigation("TimeInterval");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("JournalMVC.Models.DailyRecord", b =>
                {
                    b.HasOne("JournalMVC.Models.MonthlyRecord", "MonthlyRecord")
                        .WithMany("DailyRecords")
                        .HasForeignKey("MonthlyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyRecord");
                });

            modelBuilder.Entity("JournalMVC.Models.DailyRecord", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("JournalMVC.Models.MonthlyRecord", b =>
                {
                    b.Navigation("DailyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
